### ISSUE TITLE
The link to the paper in the ReadMe is broken

### ISSUE THREAD

**Issue by Gonzalo-Mier** [RJJxp/CoveragePlanning#1]
The paper link : https://wenku.baidu.com/view/a3ccf9abf705cc1755270974.html

**Comment by RJJxp** [comment]
Sorry for replying late. 
It's been a LONG TIME.
I am not sure whether this new link is ok
https://www.doc88.com/p-480729803489.html
But it's written in Chinese. 😔

> The paper link : https://wenku.baidu.com/view/a3ccf9abf705cc1755270974.html

**Comment by Gonzalo-Mier** [comment]
Thank you, It's still useful. No worries about the language, I'll use the  translator with the paper :smile: Thank you again

**Comment by ShikinChen** [comment]
还有这篇文章备份 百度已经删除了
